<?xml version="1.0" encoding="utf-8"?><Database Name="QLNhanSu" Class="QLNhanSuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-PA5RPVKD;Initial Catalog=QLNhanSu;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="QLNhanSu.Properties.Settings" SettingsPropertyName="QLNhanSuConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_BangLuong" Member="tbl_BangLuongs">
    <Type Name="tbl_BangLuong">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ma_nhan_vien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thang" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="luong_co_ban" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="tong_luong" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ChamCong" Member="tbl_ChamCongs">
    <Type Name="tbl_ChamCong">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ma_nhan_vien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ten_nhan_vien" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="so_ngay_nghi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thang_nam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ChucVu" Member="tbl_ChucVus">
    <Type Name="tbl_ChucVu">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="luong_co_ban" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_DuAn" Member="tbl_DuAns">
    <Type Name="tbl_DuAn">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ma" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ngay_bat_dau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngay_ket_thuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="trang_thai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mo_ta" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_NhanVien" Member="tbl_NhanViens">
    <Type Name="tbl_NhanVien">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ho" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ten" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="so_dien_thoai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="dia_chi" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ngay_sinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ten_phong_ban" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ten_chuc_vu" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cccd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="gioi_tinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PhongBan" Member="tbl_PhongBans">
    <Type Name="tbl_PhongBan">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ma" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TaiKhoan" Member="tbl_TaiKhoans">
    <Type Name="tbl_TaiKhoan">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_dang_nhap" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="mat_khau" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ThamGiaDuAn" Member="tbl_ThamGiaDuAns">
    <Type Name="tbl_ThamGiaDuAn">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ma_du_an" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_nhan_vien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vai_tro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ngay_tham_gia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngay_roi_khoi" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>