#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlNhanSu.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNhanSu")]
	public partial class QLNhanSuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_BangLuong(tbl_BangLuong instance);
    partial void Updatetbl_BangLuong(tbl_BangLuong instance);
    partial void Deletetbl_BangLuong(tbl_BangLuong instance);
    partial void Inserttbl_ChamCong(tbl_ChamCong instance);
    partial void Updatetbl_ChamCong(tbl_ChamCong instance);
    partial void Deletetbl_ChamCong(tbl_ChamCong instance);
    partial void Inserttbl_BangLuong1(tbl_BangLuong1 instance);
    partial void Updatetbl_BangLuong1(tbl_BangLuong1 instance);
    partial void Deletetbl_BangLuong1(tbl_BangLuong1 instance);
    partial void Inserttbl_ChucVu(tbl_ChucVu instance);
    partial void Updatetbl_ChucVu(tbl_ChucVu instance);
    partial void Deletetbl_ChucVu(tbl_ChucVu instance);
    partial void Inserttbl_DuAn(tbl_DuAn instance);
    partial void Updatetbl_DuAn(tbl_DuAn instance);
    partial void Deletetbl_DuAn(tbl_DuAn instance);
    partial void Inserttbl_NhanVien(tbl_NhanVien instance);
    partial void Updatetbl_NhanVien(tbl_NhanVien instance);
    partial void Deletetbl_NhanVien(tbl_NhanVien instance);
    partial void Inserttbl_PhongBan(tbl_PhongBan instance);
    partial void Updatetbl_PhongBan(tbl_PhongBan instance);
    partial void Deletetbl_PhongBan(tbl_PhongBan instance);
    partial void Inserttbl_ThamGiaDuAn(tbl_ThamGiaDuAn instance);
    partial void Updatetbl_ThamGiaDuAn(tbl_ThamGiaDuAn instance);
    partial void Deletetbl_ThamGiaDuAn(tbl_ThamGiaDuAn instance);
    partial void Inserttbl_TaiKhoan(tbl_TaiKhoan instance);
    partial void Updatetbl_TaiKhoan(tbl_TaiKhoan instance);
    partial void Deletetbl_TaiKhoan(tbl_TaiKhoan instance);
    #endregion
		
		public QLNhanSuDataContext() : 
				base(global::QlNhanSu.Properties.Settings.Default.QLNhanSuConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhanSuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhanSuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhanSuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhanSuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_BangLuong> tbl_BangLuongs
		{
			get
			{
				return this.GetTable<tbl_BangLuong>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ChamCong> tbl_ChamCongs
		{
			get
			{
				return this.GetTable<tbl_ChamCong>();
			}
		}
		
		public System.Data.Linq.Table<tbl_BangLuong1> tbl_BangLuong1s
		{
			get
			{
				return this.GetTable<tbl_BangLuong1>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ChucVu> tbl_ChucVus
		{
			get
			{
				return this.GetTable<tbl_ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DuAn> tbl_DuAns
		{
			get
			{
				return this.GetTable<tbl_DuAn>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NhanVien> tbl_NhanViens
		{
			get
			{
				return this.GetTable<tbl_NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PhongBan> tbl_PhongBans
		{
			get
			{
				return this.GetTable<tbl_PhongBan>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ThamGiaDuAn> tbl_ThamGiaDuAns
		{
			get
			{
				return this.GetTable<tbl_ThamGiaDuAn>();
			}
		}
		
		public System.Data.Linq.Table<tbl_TaiKhoan> tbl_TaiKhoans
		{
			get
			{
				return this.GetTable<tbl_TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_BangLuong")]
	public partial class tbl_BangLuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _ma_nhan_vien;
		
		private System.Nullable<System.DateTime> _thang;
		
		private System.Nullable<decimal> _luong_co_ban;
		
		private System.Nullable<decimal> _tong_luong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onma_nhan_vienChanging(System.Nullable<int> value);
    partial void Onma_nhan_vienChanged();
    partial void OnthangChanging(System.Nullable<System.DateTime> value);
    partial void OnthangChanged();
    partial void Onluong_co_banChanging(System.Nullable<decimal> value);
    partial void Onluong_co_banChanged();
    partial void Ontong_luongChanging(System.Nullable<decimal> value);
    partial void Ontong_luongChanged();
    #endregion
		
		public tbl_BangLuong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nhan_vien", DbType="Int")]
		public System.Nullable<int> ma_nhan_vien
		{
			get
			{
				return this._ma_nhan_vien;
			}
			set
			{
				if ((this._ma_nhan_vien != value))
				{
					this.Onma_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._ma_nhan_vien = value;
					this.SendPropertyChanged("ma_nhan_vien");
					this.Onma_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thang", DbType="Date")]
		public System.Nullable<System.DateTime> thang
		{
			get
			{
				return this._thang;
			}
			set
			{
				if ((this._thang != value))
				{
					this.OnthangChanging(value);
					this.SendPropertyChanging();
					this._thang = value;
					this.SendPropertyChanged("thang");
					this.OnthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luong_co_ban", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> luong_co_ban
		{
			get
			{
				return this._luong_co_ban;
			}
			set
			{
				if ((this._luong_co_ban != value))
				{
					this.Onluong_co_banChanging(value);
					this.SendPropertyChanging();
					this._luong_co_ban = value;
					this.SendPropertyChanged("luong_co_ban");
					this.Onluong_co_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_luong", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tong_luong
		{
			get
			{
				return this._tong_luong;
			}
			set
			{
				if ((this._tong_luong != value))
				{
					this.Ontong_luongChanging(value);
					this.SendPropertyChanging();
					this._tong_luong = value;
					this.SendPropertyChanged("tong_luong");
					this.Ontong_luongChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ChamCong")]
	public partial class tbl_ChamCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _ma_nhan_vien;
		
		private System.Nullable<System.DateTime> _ngay;
		
		private string _trang_thai;
		
		private string _ghi_chu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onma_nhan_vienChanging(System.Nullable<int> value);
    partial void Onma_nhan_vienChanged();
    partial void OnngayChanging(System.Nullable<System.DateTime> value);
    partial void OnngayChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    #endregion
		
		public tbl_ChamCong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nhan_vien", DbType="Int")]
		public System.Nullable<int> ma_nhan_vien
		{
			get
			{
				return this._ma_nhan_vien;
			}
			set
			{
				if ((this._ma_nhan_vien != value))
				{
					this.Onma_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._ma_nhan_vien = value;
					this.SendPropertyChanged("ma_nhan_vien");
					this.Onma_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay", DbType="Date")]
		public System.Nullable<System.DateTime> ngay
		{
			get
			{
				return this._ngay;
			}
			set
			{
				if ((this._ngay != value))
				{
					this.OnngayChanging(value);
					this.SendPropertyChanging();
					this._ngay = value;
					this.SendPropertyChanged("ngay");
					this.OnngayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="VarChar(50)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_BangLuong")]
	public partial class tbl_BangLuong1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _ma_nhan_vien;
		
		private System.Nullable<System.DateTime> _thang;
		
		private System.Nullable<decimal> _luong_co_ban;
		
		private System.Nullable<decimal> _tong_luong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onma_nhan_vienChanging(System.Nullable<int> value);
    partial void Onma_nhan_vienChanged();
    partial void OnthangChanging(System.Nullable<System.DateTime> value);
    partial void OnthangChanged();
    partial void Onluong_co_banChanging(System.Nullable<decimal> value);
    partial void Onluong_co_banChanged();
    partial void Ontong_luongChanging(System.Nullable<decimal> value);
    partial void Ontong_luongChanged();
    #endregion
		
		public tbl_BangLuong1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nhan_vien", DbType="Int")]
		public System.Nullable<int> ma_nhan_vien
		{
			get
			{
				return this._ma_nhan_vien;
			}
			set
			{
				if ((this._ma_nhan_vien != value))
				{
					this.Onma_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._ma_nhan_vien = value;
					this.SendPropertyChanged("ma_nhan_vien");
					this.Onma_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thang", DbType="Date")]
		public System.Nullable<System.DateTime> thang
		{
			get
			{
				return this._thang;
			}
			set
			{
				if ((this._thang != value))
				{
					this.OnthangChanging(value);
					this.SendPropertyChanging();
					this._thang = value;
					this.SendPropertyChanged("thang");
					this.OnthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luong_co_ban", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> luong_co_ban
		{
			get
			{
				return this._luong_co_ban;
			}
			set
			{
				if ((this._luong_co_ban != value))
				{
					this.Onluong_co_banChanging(value);
					this.SendPropertyChanging();
					this._luong_co_ban = value;
					this.SendPropertyChanged("luong_co_ban");
					this.Onluong_co_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_luong", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tong_luong
		{
			get
			{
				return this._tong_luong;
			}
			set
			{
				if ((this._tong_luong != value))
				{
					this.Ontong_luongChanging(value);
					this.SendPropertyChanging();
					this._tong_luong = value;
					this.SendPropertyChanged("tong_luong");
					this.Ontong_luongChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ChucVu")]
	public partial class tbl_ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private System.Nullable<decimal> _luong_co_ban;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void Onluong_co_banChanging(System.Nullable<decimal> value);
    partial void Onluong_co_banChanged();
    #endregion
		
		public tbl_ChucVu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="VarChar(255)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luong_co_ban", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> luong_co_ban
		{
			get
			{
				return this._luong_co_ban;
			}
			set
			{
				if ((this._luong_co_ban != value))
				{
					this.Onluong_co_banChanging(value);
					this.SendPropertyChanging();
					this._luong_co_ban = value;
					this.SendPropertyChanged("luong_co_ban");
					this.Onluong_co_banChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DuAn")]
	public partial class tbl_DuAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private string _ma;
		
		private System.Nullable<System.DateTime> _ngay_bat_dau;
		
		private System.Nullable<System.DateTime> _ngay_ket_thuc;
		
		private string _trang_thai;
		
		private string _mo_ta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnmaChanging(string value);
    partial void OnmaChanged();
    partial void Onngay_bat_dauChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_bat_dauChanged();
    partial void Onngay_ket_thucChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_ket_thucChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    #endregion
		
		public tbl_DuAn()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="VarChar(255)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="VarChar(50)")]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this.OnmaChanging(value);
					this.SendPropertyChanging();
					this._ma = value;
					this.SendPropertyChanged("ma");
					this.OnmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_bat_dau", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_bat_dau
		{
			get
			{
				return this._ngay_bat_dau;
			}
			set
			{
				if ((this._ngay_bat_dau != value))
				{
					this.Onngay_bat_dauChanging(value);
					this.SendPropertyChanging();
					this._ngay_bat_dau = value;
					this.SendPropertyChanged("ngay_bat_dau");
					this.Onngay_bat_dauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_ket_thuc", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_ket_thuc
		{
			get
			{
				return this._ngay_ket_thuc;
			}
			set
			{
				if ((this._ngay_ket_thuc != value))
				{
					this.Onngay_ket_thucChanging(value);
					this.SendPropertyChanging();
					this._ngay_ket_thuc = value;
					this.SendPropertyChanged("ngay_ket_thuc");
					this.Onngay_ket_thucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="VarChar(50)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NhanVien")]
	public partial class tbl_NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ho;
		
		private string _ten;
		
		private string _so_dien_thoai;
		
		private string _email;
		
		private string _dia_chi;
		
		private System.Nullable<System.DateTime> _ngay_sinh;
		
		private System.Nullable<int> _ma_phong_ban;
		
		private System.Nullable<int> _ma_chuc_vu;
		
		private string _cccd;
		
		private System.Nullable<bool> _gioi_tinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhoChanging(string value);
    partial void OnhoChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void Onso_dien_thoaiChanging(string value);
    partial void Onso_dien_thoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void Onngay_sinhChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_sinhChanged();
    partial void Onma_phong_banChanging(System.Nullable<int> value);
    partial void Onma_phong_banChanged();
    partial void Onma_chuc_vuChanging(System.Nullable<int> value);
    partial void Onma_chuc_vuChanged();
    partial void OncccdChanging(string value);
    partial void OncccdChanged();
    partial void Ongioi_tinhChanging(System.Nullable<bool> value);
    partial void Ongioi_tinhChanged();
    #endregion
		
		public tbl_NhanVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho", DbType="VarChar(255)")]
		public string ho
		{
			get
			{
				return this._ho;
			}
			set
			{
				if ((this._ho != value))
				{
					this.OnhoChanging(value);
					this.SendPropertyChanging();
					this._ho = value;
					this.SendPropertyChanged("ho");
					this.OnhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="VarChar(255)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="VarChar(20)")]
		public string so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(255)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="VarChar(255)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_phong_ban", DbType="Int")]
		public System.Nullable<int> ma_phong_ban
		{
			get
			{
				return this._ma_phong_ban;
			}
			set
			{
				if ((this._ma_phong_ban != value))
				{
					this.Onma_phong_banChanging(value);
					this.SendPropertyChanging();
					this._ma_phong_ban = value;
					this.SendPropertyChanged("ma_phong_ban");
					this.Onma_phong_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_chuc_vu", DbType="Int")]
		public System.Nullable<int> ma_chuc_vu
		{
			get
			{
				return this._ma_chuc_vu;
			}
			set
			{
				if ((this._ma_chuc_vu != value))
				{
					this.Onma_chuc_vuChanging(value);
					this.SendPropertyChanging();
					this._ma_chuc_vu = value;
					this.SendPropertyChanged("ma_chuc_vu");
					this.Onma_chuc_vuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cccd", DbType="VarChar(50)")]
		public string cccd
		{
			get
			{
				return this._cccd;
			}
			set
			{
				if ((this._cccd != value))
				{
					this.OncccdChanging(value);
					this.SendPropertyChanging();
					this._cccd = value;
					this.SendPropertyChanged("cccd");
					this.OncccdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioi_tinh", DbType="Bit")]
		public System.Nullable<bool> gioi_tinh
		{
			get
			{
				return this._gioi_tinh;
			}
			set
			{
				if ((this._gioi_tinh != value))
				{
					this.Ongioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._gioi_tinh = value;
					this.SendPropertyChanged("gioi_tinh");
					this.Ongioi_tinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PhongBan")]
	public partial class tbl_PhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private string _ma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnmaChanging(string value);
    partial void OnmaChanged();
    #endregion
		
		public tbl_PhongBan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="VarChar(255)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="VarChar(50)")]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this.OnmaChanging(value);
					this.SendPropertyChanging();
					this._ma = value;
					this.SendPropertyChanged("ma");
					this.OnmaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ThamGiaDuAn")]
	public partial class tbl_ThamGiaDuAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _ma_du_an;
		
		private System.Nullable<int> _ma_nhan_vien;
		
		private string _vai_tro;
		
		private System.Nullable<System.DateTime> _ngay_tham_gia;
		
		private System.Nullable<System.DateTime> _ngay_roi_khoi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onma_du_anChanging(System.Nullable<int> value);
    partial void Onma_du_anChanged();
    partial void Onma_nhan_vienChanging(System.Nullable<int> value);
    partial void Onma_nhan_vienChanged();
    partial void Onvai_troChanging(string value);
    partial void Onvai_troChanged();
    partial void Onngay_tham_giaChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_tham_giaChanged();
    partial void Onngay_roi_khoiChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_roi_khoiChanged();
    #endregion
		
		public tbl_ThamGiaDuAn()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_du_an", DbType="Int")]
		public System.Nullable<int> ma_du_an
		{
			get
			{
				return this._ma_du_an;
			}
			set
			{
				if ((this._ma_du_an != value))
				{
					this.Onma_du_anChanging(value);
					this.SendPropertyChanging();
					this._ma_du_an = value;
					this.SendPropertyChanged("ma_du_an");
					this.Onma_du_anChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nhan_vien", DbType="Int")]
		public System.Nullable<int> ma_nhan_vien
		{
			get
			{
				return this._ma_nhan_vien;
			}
			set
			{
				if ((this._ma_nhan_vien != value))
				{
					this.Onma_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._ma_nhan_vien = value;
					this.SendPropertyChanged("ma_nhan_vien");
					this.Onma_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vai_tro", DbType="VarChar(50)")]
		public string vai_tro
		{
			get
			{
				return this._vai_tro;
			}
			set
			{
				if ((this._vai_tro != value))
				{
					this.Onvai_troChanging(value);
					this.SendPropertyChanging();
					this._vai_tro = value;
					this.SendPropertyChanged("vai_tro");
					this.Onvai_troChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tham_gia", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_tham_gia
		{
			get
			{
				return this._ngay_tham_gia;
			}
			set
			{
				if ((this._ngay_tham_gia != value))
				{
					this.Onngay_tham_giaChanging(value);
					this.SendPropertyChanging();
					this._ngay_tham_gia = value;
					this.SendPropertyChanged("ngay_tham_gia");
					this.Onngay_tham_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_roi_khoi", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_roi_khoi
		{
			get
			{
				return this._ngay_roi_khoi;
			}
			set
			{
				if ((this._ngay_roi_khoi != value))
				{
					this.Onngay_roi_khoiChanging(value);
					this.SendPropertyChanging();
					this._ngay_roi_khoi = value;
					this.SendPropertyChanged("ngay_roi_khoi");
					this.Onngay_roi_khoiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TaiKhoan")]
	public partial class tbl_TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten_dang_nhap;
		
		private string _mat_khau;
		
		private System.Nullable<int> _ma_nhan_vien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onten_dang_nhapChanging(string value);
    partial void Onten_dang_nhapChanged();
    partial void Onmat_khauChanging(string value);
    partial void Onmat_khauChanged();
    partial void Onma_nhan_vienChanging(System.Nullable<int> value);
    partial void Onma_nhan_vienChanged();
    #endregion
		
		public tbl_TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dang_nhap", DbType="VarChar(255)")]
		public string ten_dang_nhap
		{
			get
			{
				return this._ten_dang_nhap;
			}
			set
			{
				if ((this._ten_dang_nhap != value))
				{
					this.Onten_dang_nhapChanging(value);
					this.SendPropertyChanging();
					this._ten_dang_nhap = value;
					this.SendPropertyChanged("ten_dang_nhap");
					this.Onten_dang_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau", DbType="VarChar(255)")]
		public string mat_khau
		{
			get
			{
				return this._mat_khau;
			}
			set
			{
				if ((this._mat_khau != value))
				{
					this.Onmat_khauChanging(value);
					this.SendPropertyChanging();
					this._mat_khau = value;
					this.SendPropertyChanged("mat_khau");
					this.Onmat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nhan_vien", DbType="Int")]
		public System.Nullable<int> ma_nhan_vien
		{
			get
			{
				return this._ma_nhan_vien;
			}
			set
			{
				if ((this._ma_nhan_vien != value))
				{
					this.Onma_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._ma_nhan_vien = value;
					this.SendPropertyChanged("ma_nhan_vien");
					this.Onma_nhan_vienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
