<?xml version="1.0" encoding="utf-8"?><Database Name="QLNhanSu" Class="QLNhanSuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-5T71VEB\SQLEXPRESS;Initial Catalog=QLNhanSu;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="QlNhanSu.Properties.Settings" SettingsPropertyName="QLNhanSuConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BangLuong" Member="BangLuongs">
    <Type Name="BangLuong">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thang" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LuongCoBan" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TongLuong" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThamGiaDuAn" Member="ThamGiaDuAns">
    <Type Name="ThamGiaDuAn">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDuAn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VaiTro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayThamGia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayRoiKhoi" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChamCong" Member="ChamCongs">
    <Type Name="ChamCong">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenNhanVien" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SoNgayNghi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThangNam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChucVu" Member="ChucVus">
    <Type Name="ChucVu">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChucVu" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="LuongCoBan" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DuAn" Member="DuAns">
    <Type Name="DuAn">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDuAn" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MaDuAn" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ho" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PhongBan" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhongBan" Member="PhongBans">
    <Type Name="PhongBan">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhongBan" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MaPhongBan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>